### ISSUE TITLE
Kumiho.org SPA 옵션 문제 있습니다.

### ISSUE THREAD

**Issue by benjioh5** [KumihoProject/Kumiho#10]
URL 관련 파싱 문제인지, Kumiho.org에서 Dashboard에서 새로고침하면 다음과 같이 뜹니다. 아마도, SPA 관련 설정이 잘못 된 거 같습니다.
<img width="531" alt="스크린샷 2020-05-26 오후 10 33 48" src="https://user-images.githubusercontent.com/4755202/82907045-13dca600-9fa1-11ea-9866-512422e16c36.png">

**Comment by elwlwlwk** [comment]
해당문제는 수정하도록 하겠습니다.
일단 http://kumiho.klay/dashboard/benjioh5.klay 에서 이용 부탁드립니다.

**Comment by elwlwlwk** [comment]
수정되었습니다.
